# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        MainWindow.setMaximumSize(QtCore.QSize(600, 600))
        font = QtGui.QFont()
        font.setPointSize(15)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calculator_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.calculator_label.setGeometry(QtCore.QRect(230, 10, 131, 21))
        self.calculator_label.setMaximumSize(QtCore.QSize(131, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.calculator_label.setFont(font)
        self.calculator_label.setObjectName("calculator_label")
        self.firstnumber_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.firstnumber_label.setGeometry(QtCore.QRect(10, 70, 121, 16))
        self.firstnumber_label.setMaximumSize(QtCore.QSize(121, 16))
        self.firstnumber_label.setObjectName("firstnumber_label")
        self.firtnumber_text = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.firtnumber_text.setGeometry(QtCore.QRect(180, 59, 391, 31))
        self.firtnumber_text.setMaximumSize(QtCore.QSize(391, 31))
        self.firtnumber_text.setText("")
        self.firtnumber_text.setObjectName("firtnumber_text")
        self.secondnumber_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.secondnumber_label.setGeometry(QtCore.QRect(10, 140, 151, 16))
        self.secondnumber_label.setMaximumSize(QtCore.QSize(151, 16))
        self.secondnumber_label.setObjectName("secondnumber_label")
        self.secondnumber_text = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.secondnumber_text.setGeometry(QtCore.QRect(180, 129, 391, 31))
        self.secondnumber_text.setMaximumSize(QtCore.QSize(391, 31))
        self.secondnumber_text.setObjectName("secondnumber_text")
        self.equationtype_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.equationtype_label.setGeometry(QtCore.QRect(10, 220, 141, 21))
        self.equationtype_label.setMaximumSize(QtCore.QSize(141, 21))
        self.equationtype_label.setObjectName("equationtype_label")
        self.equationtype_text = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.equationtype_text.setGeometry(QtCore.QRect(180, 209, 391, 31))
        self.equationtype_text.setMaximumSize(QtCore.QSize(391, 31))
        self.equationtype_text.setObjectName("equationtype_text")
        self.answer_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.answer_label.setGeometry(QtCore.QRect(10, 540, 101, 16))
        self.answer_label.setMaximumSize(QtCore.QSize(101, 16))
        self.answer_label.setObjectName("answer_label")
        self.answer_text = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.answer_text.setGeometry(QtCore.QRect(180, 530, 391, 31))
        self.answer_text.setMaximumSize(QtCore.QSize(391, 31))
        self.answer_text.setText("")
        self.answer_text.setObjectName("answer_text")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(50, 280, 511, 141))
        self.textBrowser.setMaximumSize(QtCore.QSize(511, 141))
        self.textBrowser.setObjectName("textBrowser")
        self.calculate_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.calculate_button.setGeometry(QtCore.QRect(60, 450, 141, 51))
        self.calculate_button.setObjectName("calculate_button")
        self.clear_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.clear_button.setGeometry(QtCore.QRect(400, 450, 141, 51))
        self.clear_button.setObjectName("clear_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.calculator_label.setText(_translate("MainWindow", "Calculator"))
        self.firstnumber_label.setText(_translate("MainWindow", "First Number:"))
        self.secondnumber_label.setText(_translate("MainWindow", "Second Number:"))
        self.equationtype_label.setText(_translate("MainWindow", "Equation Type:"))
        self.answer_label.setText(_translate("MainWindow", "Answer:"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Equation Type must use a symbol: Addition (+), Subtraction (-), Multiplication (x), Division (/), Floored Division (//), Modulo Division (%), exponential (^)</p></body></html>"))
        self.calculate_button.setText(_translate("MainWindow", "Calculate"))
        self.clear_button.setText(_translate("MainWindow", "Clear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())